/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.6.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)

    // This dependency is used by the application.
    implementation(libs.guava)

    // Image metadata extraction (EXIF/IPTC/XMP) for JPG/PNG and others.
    implementation(libs.metadata.extractor)

    // build hashes out of images
    implementation(libs.jimage.hash)

    // read xmp files
    implementation(libs.xmpcore)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

javafx {
    version = "21.0.8"
    modules = listOf("javafx.base", "javafx.graphics", "javafx.swing")
}

application {
    // Define the main class for the application.
    mainClass = "de.vonrauchhaupt.picutils.Scanner"
}
