package de.vonrauchhaupt.picutils.model;

import java.util.HashMap;
import java.util.Map;

public enum MetadataTagEnum {
    IMAGE_WIDTH("Image Width"), // Pixel width of the image.
    IMAGE_HEIGHT("Image Height"), // Pixel height of the image.
    EXIF_IMAGE_WIDTH("Exif Image Width"), // Width from EXIF dimension fields.
    EXIF_IMAGE_HEIGHT("Exif Image Height"), // Height from EXIF dimension fields.
    PROFILE_DATE_TIME("Profile Date/Time", true), // ICC profile creation timestamp.
    LAST_MODIFICATION_TIME("Last Modification Time", true), // Last modification time recorded in metadata.
    FILE_NAME("File Name"), // Source file name.
    FILE_SIZE("File Size"), // File size as reported by metadata extractor.
    FILE_MODIFIED_DATE("File Modified Date", true), // Filesystem modified timestamp string.
    UNIT_SPECIFIER("Unit Specifier"), // Unit for density values (e.g., metres).
    PIXELS_PER_UNIT_X("Pixels Per Unit X"), // Horizontal pixel density.
    PIXELS_PER_UNIT_Y("Pixels Per Unit Y"), // Vertical pixel density.
    RESOLUTION_UNITS("Resolution Units"), // JFIF resolution unit.
    RESOLUTION_UNIT("Resolution Unit"), // EXIF resolution unit.
    X_RESOLUTION("X Resolution"), // Horizontal resolution value.
    Y_RESOLUTION("Y Resolution"), // Vertical resolution value.
    ORIENTATION("Orientation", true), // EXIF orientation flag.
    DATE_TIME("Date/Time", true), // Generic EXIF date/time field.
    DATE_TIME_ORIGINAL("Date/Time Original", true), // Original capture/create timestamp.
    GPS_LATITUDE_REF("GPS Latitude Ref", true), // Latitude hemisphere reference (N/S).
    GPS_LATITUDE("GPS Latitude", true), // Latitude coordinate.
    GPS_LONGITUDE_REF("GPS Longitude Ref", true), // Longitude hemisphere reference (E/W).
    GPS_LONGITUDE("GPS Longitude", true), // Longitude coordinate.
    KEYWORDS("Keywords", true), // IPTC keywords/tags.
    IMAGE_DESCRIPTION("Image Description", true),
    JPEG_COMMENT("JPEG Comment", true),
    BRIGHTNESS("Brightness"),
    RELEASE_MODE("Release Mode"),
    ENVELOPE_RECORD_VERSION("Envelope Record Version"),
    CUSTOM_PICTURE_STYLE_FILE_NAME("Custom Picture Style File Name"),
    WHITE_BALANCE_2("White Balance 2"),
    GPS_DEST_BEARING("GPS Dest Bearing"),
    VIGNETTE_CONTROL("Vignette Control"),
    LENS_MODEL("Lens Model"),
    SENSOR_INFORMATION_ARRAY("Sensor Information Array"),
    VIEWING_CONDITIONS("Viewing Conditions"),
    COLOR_DATA_ARRAY_1("Color Data Array 1"),
    GAMMA("Gamma"),
    AF_TUNE("AF Tune"),
    VIGNETTING_CORRECTION("Vignetting Correction"),
    OWNER_NAME("Owner Name"),
    CAMERA_SERIAL_NUMBER("Camera Serial Number"),
    STRIP_BYTE_COUNTS("Strip Byte Counts"),
    WINDOWS_XP_SUBJECT("Windows XP Subject"),
    FLASH_ENERGY("Flash Energy"),
    POWER_UP_TIME("Power Up Time"),
    MULTI_FRAME_NOISE_REDUCTION("Multi Frame Noise Reduction"),
    TILE_LENGTH("Tile Length"),
    TIME_ZONE("Time Zone"),
    PANASONIC_TITLE2("Panasonic Title (2)"),
    PROCESSING_INFORMATION_ARRAY("Processing Information Array"),
    PRIMARY_AF_POINT_1("Primary AF Point 1"),
    IMAGE_DATA_SIZE("Image Data Size"),
    CROP_HIGH_SPEED("Crop High Speed"),
    SERIAL_NUMBER_FORMAT("Serial Number Format"),
    GPS_TIME_STAMP("GPS Time-Stamp"),
    GPS_MAP_DATUM("GPS Map Datum"),
    IMAGE_BOUNDARY("Image Boundary"),
    DOCUMENT_NAME("Document Name"),
    RECOMMENDED_EXPOSURE_INDEX("Recommended Exposure Index"),
    INTELLIGENT_AUTO("Intelligent Auto"),
    MACRO("Macro"),
    HDR("HDR"),
    AUTO_FLASH_MODE("Auto Flash Mode"),
    FILE_INFO_ARRAY("File Info Array"),
    DIGITAL_VARI_PROGRAM("Digital Vari Program"),
    COLOR_BALANCE_ARRAY("Color Balance Array"),
    MULTI_EXPOSURE("Multi Exposure"),
    AF_POINT_COUNT("AF Point Count"),
    EXPOSURE_DIFFERENCE("Exposure Difference"),
    SUB_SEC_TIME("Sub-Sec Time"),
    OPTO_ELECTRIC_CONVERSION_FUNCTION("Opto-electric Conversion Function (OECF)"),
    MEASUREMENT("Measurement"),
    AUTO_PORTRAIT_FRAMING("Auto Portrait Framing"),
    MEASURED_COLOR_ARRAY("Measured Color Array"),
    CFA_PATTERN("CFA Pattern"),
    PREVIEW_IMAGE_SIZE("Preview Image Size"),
    DIGITAL_TIME_CREATED("Digital Time Created"),
    CUSTOM_FUNCTIONS("Custom Functions"),
    SERIAL_INFO_ARRAY("Serial Info Array"),
    SHOT_INFO("Shot Info"),
    COLOR_DATA_ARRAY_2("Color Data Array 2"),
    FILE_FORMAT("File Format"),
    SUBJECT_LOCATION("Subject Location"),
    DEVICE_ATTRIBUTES("Device attributes"),
    DUST_REMOVAL_DATA("Dust Removal Data"),
    ISO_INFO("ISO Info"),
    AF_AREA_HEIGHT("AF Area Height"),
    PRIMARY_CHROMATICITIES("Primary Chromaticities"),
    PLANAR_CONFIGURATION("Planar Configuration"),
    RELATED_SOUND_FILE("Related Sound File"),
    AF_MODE("AF Mode"),
    DIGITAL_DATE_CREATED("Digital Date Created"),
    AF_AREA_X_POSITIONS("AF Area X Positions"),
    STRIP_OFFSETS("Strip Offsets"),
    WHITE_POINT("White Point"),
    PROGRAM_SHIFT("Program Shift"),
    AUTO_FLASH_COMPENSATION("Auto Flash Compensation"),
    WORLD_TIME("World Time"),
    SCENE_ASSIST("Scene Assist"),
    SONY_MODEL_ID("Sony Model ID"),
    GPS_STATUS("GPS Status"),
    GPS_DATE_STAMP("GPS Date Stamp"),
    PREVIEW_IMAGE("Preview Image"),
    AF_INFO_2("AF Info 2"),
    RATING_PERCENT("Rating Percent"),
    PLUG_IN_2_DATA("Plug-in 2 Data"),
    FACE_DETECT_ARRAY_2("Face Detect Array 2"),
    LENS_SERIAL_NUMBER("Lens Serial Number"),
    FILE_LENGTH("File Length"),
    FLASH_BRACKET_COMPENSATION("Flash Bracket Compensation"),
    LENS_MAKE("Lens Make"),
    AF_AREA_Y_POSITIONS("AF Area Y Positions"),
    CONTACT("Contact"),
    PRINT_INFO("Print Info"),
    HOST_COMPUTER("Host Computer"),
    DISTORT_INFO("Distort Info"),
    AF_IMAGE_HEIGHT("AF Image Height"),
    FULL_IMAGE_SIZE("Full Image Size"),
    CRW_PARAMETERS("CRW Parameters"),
    LENS_DATA("Lens Data"),
    GPS_IMG_DIRECTION("GPS Img Direction"),
    VR_INFO("VR Info"),
    ORIGINAL_TRANSMISSION_REFERENCE("Original Transmission Reference"),
    AE_BRACKET_COMPENSATION("AE Bracket Compensation"),
    PANASONIC_TITLE("Panasonic Title"),
    GPS_AREA_INFORMATION("GPS Area Information"),
    COLOR_MODE_SETTING("Color Mode Setting"),
    GPS_SPEED_REF("GPS Speed Ref"),
    VIEWING_CONDITIONS_DESCRIPTION("Viewing Conditions Description"),
    COLOR_INFO_ARRAY("Color Info Array"),
    LATERAL_CHROMATIC_ABERRATION("Lateral Chromatic Aberration"),
    VIGNETTING_CORRECTION_ARRAY_1("Vignetting Correction Array 1"),
    CMM_FLAGS("CMM Flags"),
    DEVICE_SETTING_DESCRIPTION("Device Setting Description"),
    RETOUCH_HISTORY("Retouch History"),
    TIME_ZONE_DIGITIZED("Time Zone Digitized"),
    WINDOWS_XP_KEYWORDS("Windows XP Keywords"),
    GPS_SPEED("GPS Speed"),
    WHITE_BALANCE_RB_COEFFICIENTS("White Balance RB Coefficients"),
    GPS_SATELLITES("GPS Satellites"),
    FLASH_INFO("Flash Info"),
    SOFT_SKIN_EFFECT("Soft Skin Effect"),
    AF_AREA_WIDTH("AF Area Width"),
    GPS_DOP("GPS DOP"),
    DEVICE_MODEL("Device model"),
    WINDOWS_XP_COMMENT("Windows XP Comment"),
    AF_IMAGE_WIDTH("AF Image Width"),
    MAC_PRINT_INFO("Mac Print Info"),
    LENS_INFO_ARRAY("Lens Info Array"),
    GPS_MEASURE_MODE("GPS Measure Mode"),
    PANORAMA("Panorama"),
    TECHNOLOGY("Technology"),
    MAKERNOTE("Makernote"),
    CROP_INFO("Crop Info"),
    YCBCR_COEFFICIENTS("YCbCr Coefficients"),
    LENS("Lens"),
    ANTI_BLUR("Anti Blur"),
    FLASH_LEVEL("Flash Level"),
    RETOUCH_INFO("Retouch Info"),
    AMBIANCE_INFO_ARRAY("Ambiance Info Array"),
    SUBJECT_DISTANCE("Subject Distance"),
    GPS_ALTITUDE_REF("GPS Altitude Ref"),
    WHITE_BALANCE_FINE("White Balance Fine"),
    TIME_ZONE_ORIGINAL("Time Zone Original"),
    LIGHTING_OPTIMIZER_ARRAY("Lighting Optimizer Array"),
    UNIQUE_IMAGE_ID("Unique Image ID"),
    CUSTOM_FUNCTIONS_ARRAY_2("Custom Functions Array 2"),
    LENS_SPECIFICATION("Lens Specification"),
    VIGNETTING_CORRECTION_ARRAY_2("Vignetting Correction Array 2"),
    ACTIVE_D_LIGHTING("Active D-Lighting"),
    FLASH_USED("Flash Used"),
    DISTORTION_CORRECTION("Distortion Correction"),
    EXPOSURE_TUNING("Exposure Tuning"),
    GPS_DEST_BEARING_REF("GPS Dest Bearing Ref"),
    FILE_INFO("File Info"),
    PICTURE_EFFECT("Picture Effect"),
    GRAY_TRC("Gray TRC"),
    GPS_HORIZONTAL_POSITIONING_ERROR("GPS Horizontal Positioning Error"),
    VALID_AF_POINT_COUNT("Valid AF Point Count"),
    COLOR_BALANCE("Color Balance"),
    ORIGINAL_DECISION_DATA_OFFSET("Original Decision Data Offset"),
    WINDOWS_XP_TITLE("Windows XP Title"),
    BODY_SERIAL_NUMBER("Body Serial Number"),
    FACE_DETECT_ARRAY_1("Face Detect Array 1"),
    URL("URL"),
    AF_ILLUMINATOR("AF Illuminator"),
    GPS_PROCESSING_METHOD("GPS Processing Method"),
    LENS_STOPS("Lens Stops"),
    GPS_IMG_DIRECTION_REF("GPS Img Direction Ref"),
    SUB_SEC_TIME_DIGITIZED("Sub-Sec Time Digitized"),
    WB_SHIFT_AMBER_MAGENTA("WB Shift Amber/Magenta"),
    EXPOSURE_SEQUENCE_NUMBER("Exposure Sequence Number"),
    FILTER_INFO_ARRAY("Filter Info Array"),
    TILE_WIDTH("Tile Width"),
    ROWS_PER_STRIP("Rows Per Strip"),
    BLACK_LEVEL("Black Level"),
    SHOOTING_MODE("Shooting Mode"),
    LUMINANCE("Luminance"),
    PRIMARY_AF_POINT_2("Primary AF Point 2"),
    EXPOSURE_INDEX("Exposure Index"),
    PLUG_IN_1_DATA("Plug-in 1 Data"),
    GPS_ALTITUDE("GPS Altitude"),
    JPEG_QUALITY("JPEG Quality"),
    URL_LIST("URL List",true),
    TIME_CREATED("Time Created", true),
    AEB_BRACKET_VALUE("AEB Bracket Value"),
    AE_SETTING("AE Setting"),
    AF_INFO_ARRAY_2("AF Info Array 2"),
    AF_POINTS_IN_FOCUS("AF Points in Focus"),
    AF_POINT_SELECTED("AF Point Selected"),
    APERTURE_VALUE("Aperture Value"),
    APPLICATION_RECORD_VERSION("Application Record Version"), // IPTC application record version.
    ARTIST("Artist"),
    ASPECT_INFORMATION_ARRAY("Aspect Information Array"),
    AUTO_EXPOSURE_BRACKETING("Auto Exposure Bracketing"),
    AUTO_ISO("Auto ISO"),
    AUTO_ROTATE("Auto Rotate"),
    BACKGROUND_COLOR("Background Color"), // Suggested background color.
    BASE_ISO("Base ISO"),
    BITS_PER_SAMPLE("Bits Per Sample"), // Bit depth per channel/sample.
    BLUE_COLORANT("Blue Colorant"), // Blue primary colorant coordinates.
    BLUE_TRC("Blue TRC"), // Blue tone response curve definition.
    BRIGHTNESS_VALUE("Brightness Value"),
    BULB_DURATION("Bulb Duration"),
    BY_LINE("By-line"), // Creator/author credit line.
    BY_LINE_TITLE("By-line Title"), // Creator role/title.
    CAMERA_INFO("Camera Info"),
    CAMERA_INFO_ARRAY("Camera Info Array"),
    CAMERA_OWNER_NAME("Camera Owner Name"),
    CAMERA_SETTINGS("Camera Settings"),
    CAMERA_TEMPERATURE("Camera Temperature"),
    CAMERA_TYPE("Camera Type"),
    CANON_MODEL_ID("Canon Model ID"),
    CAPTION_ABSTRACT("Caption/Abstract"), // IPTC caption or abstract text.
    CAPTION_DIGEST("Caption Digest"),
    CAPTION_WRITER_EDITOR("Caption Writer/Editor"),
    CATEGORIES("Categories"),
    CATEGORY("Category"), // IPTC category code.
    CHROMATICITY("Chromaticity"), // Chromaticity tag data.
    CHROMATIC_ADAPTATION("Chromatic Adaptation"), // Chromatic adaptation matrix/metadata.
    CLASS("Class"), // ICC profile class (display, input, etc.).
    CMM_TYPE("CMM Type"), // Color Management Module signature/type.
    CODED_CHARACTER_SET("Coded Character Set"),
    COLOR_COMPENSATION_FILTER("Color Compensation Filter"),
    COLOR_HALFTONING_INFORMATION("Color Halftoning Information"),
    COLOR_MODE("Color Mode"),
    COLOR_SPACE1("Color space"), // Declared color space used by the image/profile.
    COLOR_SPACE2("Color Space"), // Declared color space used by the image/profile.
    COLOR_TEMPERATURE("Color Temperature"),
    COLOR_TONE("Color Tone"),
    COLOR_TRANSFER_FUNCTIONS("Color Transfer Functions"),
    COLOR_TRANSFORM("Color Transform"),
    COLOR_TYPE("Color Type"), // PNG/JPEG color model/type information.
    COMPONENTS_CONFIGURATION("Components Configuration"), // EXIF component layout/configuration.
    COMPONENT_1("Component 1"), // Details for first component/channel.
    COMPONENT_2("Component 2"), // Details for second component/channel.
    COMPONENT_3("Component 3"), // Details for third component/channel.
    COMPRESSED_BITS_PER_PIXEL("Compressed Bits Per Pixel"),
    COMPRESSION("Compression"),
    COMPRESSION_TYPE("Compression Type"), // Compression algorithm/mode used.
    CONTINUOUS_DRIVE_MODE("Continuous Drive Mode"),
    CONTRAST("Contrast"),
    CONTROL_MODE("Control Mode"),
    COPYRIGHT("Copyright"),
    COPYRIGHT_FLAG("Copyright Flag"),
    COPYRIGHT_NOTICE("Copyright Notice"), // IPTC copyright statement.
    COUNTRY_PRIMARY_LOCATION_CODE("Country/Primary Location Code"), // IPTC country code.
    COUNTRY_PRIMARY_LOCATION_NAME("Country/Primary Location Name"), // IPTC country name.
    CREDIT("Credit"), // Credit provider line.
    CUSTOM_RENDERED("Custom Rendered"),
    DATA_PRECISION("Data Precision"), // JPEG sample precision.
    DATE_CREATED("Date Created"), // IPTC creation date.
    DATE_STAMP_MODE("Date Stamp Mode"),
    DATE_TIME_DIGITIZED("Date/Time Digitized"),
    DCT_ENCODE_VERSION("DCT Encode Version"),
    DETECTED_FILE_TYPE_LONG_NAME("Detected File Type Long Name"), // Full detected file type name.
    DETECTED_FILE_TYPE_NAME("Detected File Type Name"), // Short detected file type (e.g., PNG).
    DETECTED_MIME_TYPE("Detected MIME Type"), // Detected MIME type.
    DEVICE_MANUFACTURER("Device manufacturer"),
    DEVICE_MFG_DESCRIPTION("Device Mfg Description"), // Device manufacturer description.
    DEVICE_MODEL_DESCRIPTION("Device Model Description"), // Device model description.
    DIGITAL_ZOOM("Digital Zoom"),
    DIGITAL_ZOOM_RATIO("Digital Zoom Ratio"),
    GAIN_CONTROL("Gain Control"),
    DATA_DUMP("Data Dump"),
    IMAGE_ADJUSTMENT("Image Adjustment"),
    ADAPTER("Adapter"),
    NOISE_REDUCTION("Noise Reduction"),
    PREVIEW_IFD("Preview IFD"),
    SHARPENING("Sharpening"),
    AF_TYPE("AF Type"),
    ISO1("ISO"),
    ISO2("Iso"),
    MANUAL_FOCUS_DISTANCE("Manual Focus Distance"),
    QUALITY_FILE_FORMAT("Quality & File Format"),
    AF_FOCUS_POSITION("AF Focus Position"),
    ISO_MODE("ISO Mode"),
    FLASH_SYNC_MODE("Flash Sync Mode"),
    SUBJECT_DISTANCE_RANGE("Subject Distance Range"),
    DISPLAY_APERTURE("Display Aperture"),
    DYNAMIC_RANGE_OPTIMIZER("Dynamic Range Optimizer"),
    EASY_SHOOTING_MODE("Easy Shooting Mode"),
    EXIF_VERSION("Exif Version"), // EXIF specification version.
    EXPECTED_FILE_NAME_EXTENSION("Expected File Name Extension"), // Expected extension for detected type.
    EXPOSURE_BIAS_VALUE("Exposure Bias Value"),
    EXPOSURE_COMPENSATION("Exposure Compensation"),
    EXPOSURE_MODE("Exposure Mode"),
    EXPOSURE_PROGRAM("Exposure Program"),
    EXPOSURE_TIME("Exposure Time"),
    EXTRA_INFO("Extra Info"),
    FILE_SOURCE("File Source"),
    FILTER_METHOD("Filter Method"), // PNG filter method before compression.
    FIRMWARE_REVISION("Firmware Revision"),
    FIRMWARE_VERSION("Firmware Version"),
    FLAGS_0("Flags 0"),
    FLAGS_1("Flags 1"),
    FLASH("Flash"),
    FLASH_ACTIVITY("Flash Activity"),
    FLASH_DETAILS("Flash Details"),
    FLASH_EXPOSURE_COMPENSATION("Flash Exposure Compensation"),
    FLASH_GUIDE_NUMBER("Flash Guide Number"),
    FLASH_MODE("Flash Mode"),
    FLASH_OUTPUT("Flash Output"),
    FLASH_PIX_VERSION("FlashPix Version"), // FlashPix compatibility version.
    FOCAL_LENGTH("Focal Length"),
    FOCAL_LENGTH_35("Focal Length 35"),
    FOCAL_PLANE_RESOLUTION_UNIT("Focal Plane Resolution Unit"),
    FOCAL_PLANE_X_RESOLUTION("Focal Plane X Resolution"),
    FOCAL_PLANE_Y_RESOLUTION("Focal Plane Y Resolution"),
    FOCAL_UNITS_PER_MM("Focal Units per mm"),
    FOCUS_CONTINUOUS("Focus Continuous"),
    FOCUS_DISTANCE_LOWER("Focus Distance Lower"),
    FOCUS_DISTANCE_UPPER("Focus Distance Upper"),
    FOCUS_INFO("Focus Info"),
    FOCUS_MODE("Focus Mode"),
    FOCUS_TYPE("Focus Type"),
    F_NUMBER1("F Number"),
    F_NUMBER2("F-Number"),
    GLOBAL_ALTITUDE("Global Altitude"),
    GLOBAL_ANGLE("Global Angle"),
    GPS_VERSION_ID("GPS Version ID"),
    GREEN_COLORANT("Green Colorant"), // Green primary colorant coordinates.
    GREEN_TRC("Green TRC"), // Green tone response curve definition.
    GRID_AND_GUIDES_INFORMATION("Grid and Guides Information"),
    HEADLINE("Headline"), // IPTC headline/title.
    HIGH_ISO_NOISE_REDUCTION("High ISO Noise Reduction"),
    ICC_PROFILE_NAME("ICC Profile Name"), // Name/label of embedded ICC profile.
    ICC_UNTAGGED_PROFILE("ICC Untagged Profile"),
    IMAGE_NUMBER("Image Number"),
    IMAGE_QUALITY("Image Quality"),
    IMAGE_SIZE("Image Size"),
    IMAGE_STABILISATION("Image Stabilisation"),
    IMAGE_TYPE("Image Type"),
    IMAGE_UNIQUE_ID("Image Unique ID"),
    INTERLACE_METHOD("Interlace Method"), // Interlacing strategy (e.g., none/Adam7).
    INTEROPERABILITY_INDEX("Interoperability Index"),
    INTEROPERABILITY_VERSION("Interoperability Version"),
    ISO_SPEED_RATINGS("ISO Speed Ratings"),
    LAYERS_GROUP_INFORMATION("Layers Group Information"),
    LAYER_GROUPS_ENABLED_ID("Layer Groups Enabled ID"),
    LAYER_SELECTION_IDS("Layer Selection IDs"),
    LAYER_STATE_INFORMATION("Layer State Information"),
    LENS_ID("Lens ID"),
    LENS_SPEC("Lens Spec"),
    LENS_TYPE("Lens Type"),
    LONG_EXPOSURE_NOISE_REDUCTION("Long Exposure Noise Reduction"),
    LONG_FOCAL_LENGTH("Long Focal Length"),
    MACRO_MODE("Macro Mode"),
    MAKE("Make"), // Camera/scanner manufacturer.
    MANUAL_FLASH_OUTPUT("Manual Flash Output"),
    MAX_APERTURE("Max Aperture"),
    MAX_APERTURE_VALUE("Max Aperture Value"),
    MEASURED_EV("Measured EV"),
    MEASURED_EV_2("Measured EV 2"),
    MEDIA_BLACK_POINT("Media Black Point"),
    MEDIA_WHITE_POINT("Media White Point"), // White point chromaticity in profile.
    METERING_MODE("Metering Mode"),
    MIN_APERTURE("Min Aperture"),
    MODEL("Model"), // Camera/scanner model.
    MY_COLORS("My Colors"),
    GIF_FORMAT_VERSION("GIF Format Version"),
    CLEAR_RETOUCH("Clear Retouch"),
    BRACKET_SETTINGS("Bracket Settings"),
    BURST_MODE_2("Burst Mode 2"),
    DYNAMIC_RANGE("Dynamic Range"),
    MANUAL_FLASH_STRENGTH("Manual Flash Strength"),
    ART_FILTER("Art Filter"),
    ADVANCED_SCENE_MODE("Advanced Scene Mode"),
    DATE_TIME_UTC("Date Time UTC"),
    CITY_2("City 2"),
    SWEEP_PANORAMA_FIELD_OF_VIEW("Sweep Panorama Field Of View"),
    DEVICE_TYPE("Device Type"),
    CONTRAST_MODE("Contrast Mode"),
    MAKERNOTE_UNKNOWN_1("Makernote Unknown 1"),
    PANASONIC_IMAGE_HEIGHT("Panasonic Image Height"),
    COLOR_EFFECT("Color Effect"),
    PREVIEW_IMAGE_VALID("Preview Image Valid"),
    EXTENDER_FIRMWARE_VERSION("Extender Firmware Version"),
    MAX_FOCAL_LENGTH("Max Focal Length"),
    PICTURE_MODE_EFFECT("Picture Mode Effect"),
    KEYSTONE_DIRECTION("Keystone Direction"),
    PICTURE_MODE_SHARPNESS("Picture Mode Sharpness"),
    AF_AREA_MODE("AF Area Mode"),
    APS_C_SIZE_CAPTURE("APS-C Size Capture"),
    FACE_RECOGNITION_INFO("Face Recognition Info"),
    COUNTRY("Country"),
    MAKERNOTE_UNKNOWN_6("Makernote Unknown 6"),
    FOCUS_PROCESS("Focus Process"),
    EXTERNAL_FLASH("External Flash"),
    USER_INPUT_FLAG("User Input Flag"),
    TITLE("Title"),
    FLASH_FIRED("Flash Fired"),
    AF_POINT_POSITION("Af Point Position"),
    TRANSPARENT_COLOR_INDEX("Transparent Color Index"),
    FLASH_STATUS("Flash Status"),
    PANASONIC_IMAGE_WIDTH("Panasonic Image Width"),
    DATE_TIME_STAMP("Date/Time Stamp"),
    LANDMARK("Landmark"),
    FOCUSING_MODE("Focusing Mode"),
    RAW_DEV_GRAY_POINT("Raw Dev Gray Point"),
    ISO_SETTING("ISO Setting"),
    MACRO_LED("Macro LED"),
    ACCELEROMETER_Y("Accelerometer Y"),
    FOCUS_WARNING("Focus Warning"),
    SENSOR_TEMPERATURE("Sensor Temperature"),
    X_PIXELS_PER_METER("X Pixels per Meter"),
    FACE_DETECT_AREA("Face Detect Area"),
    HEADER_SIZE("Header Size"),
    EPOCH("Epoch"),
    FILTER("Filter"),
    SHUTTER_TYPE("Shutter Type"),
    GAIN_BASE("Gain Base"),
    MULTIPLE_EXPOSURE_MODE("Multiple Exposure Mode"),
    PITCH_ANGLE("Pitch Angle"),
    PICTURE_CONTROL_BASE("Picture Control Base"),
    RAW_DEV_NOISE_REDUCTION("Raw Dev Noise Reduction"),
    DRIVE_MODE("Drive Mode"),
    FOCUS_PIXEL("Focus Pixel"),
    MODIFIED_SATURATION("Modified Saturation"),
    BACKGROUND_COLOR_INDEX("Background Color Index"),
    SCENE_DETECT_DATA("Scene Detect Data"),
    RAW_DEV_SETTINGS("Raw Dev Settings"),
    NUMBER_OF_DETECTED_FACES("Number of Detected Faces"),
    WB_RB_LEVELS("WB RB Levels"),
    SPECIAL_MODE("Special Mode"),
    COLOR_SATURATION("Color Saturation"),
    EXTENDED_WB_DETECT("Extended WB Detect"),
    WHITE_BALANCE_TEMPERATURE("White Balance Temperature"),
    PICTURE_MODE_CONTRAST("Picture Mode Contrast"),
    ASPECT_RATIO("Aspect Ratio"),
    AUDIO("Audio"),
    FINEPIX_COLOR_SETTING("FinePix Color Setting"),
    MAKERNOTE_UNKNOWN_4("Makernote Unknown 4"),
    TRANSFORM("Transform"),
    FLASH_TYPE("Flash Type"),
    ZOOM_STEP_COUNT("Zoom Step Count"),
    WIDTH("Width"),
    TEXT_STAMP_1("Text Stamp 1"),
    TOUCH_AE("Touch AE"),
    HAS_LOCAL_COLOUR_TABLE("Has Local Colour Table"),
    FOCUS_STEP_COUNT("Focus Step Count"),
    FOCUS_STEP_NEAR("Focus Step Near"),
    ACCELEROMETER_Z("Accelerometer Z"),
    TIMER_RECORDING("Timer Recording"),
    PANORAMA_MODE("Panorama Mode"),
    INTELLIGENT_D_RANGE("Intelligent D-Range"),
    EXTENDER_SERIAL_NUMBER("Extender Serial Number"),
    ASPECT_FRAME("Aspect Frame"),
    FIRMWARE("Firmware"),
    AF_AREAS("AF Areas"),
    CAMERA_UPTIME("Camera Uptime"),
    MAKER_NOTE_VERSION("Maker Note Version"),
    QUALITY_MODE("Quality Mode"),
    FLASH_INTENSITY("Flash Intensity"),
    SELF_TIMER("Self Timer"),
    BURST_MODE("Burst Mode"),
    PROGRAM_ISO("Program ISO"),
    TRANSFORM_1("Transform 1"),
    WHITE_BALANCE_ADJUST_GM("White Balance Adjust (GM)"),
    PICT_INFO("Pict Info"),
    RAW_DEV_MEMORY_COLOR_EMPHASIS("Raw Dev Memory Color Emphasis"),
    TRANSPARENT_COLOR_FLAG("Transparent Color Flag"),
    KEYSTONE_COMPENSATION("Keystone Compensation"),
    BW_MODE("BW Mode"),
    WORLD_TIME_LOCATION("World Time Location"),
    PICTURE_MODE_BW_FILTER("Picture Mode BW Filter"),
    PALETTE_COLOUR_COUNT("Palette Colour Count"),
    CONVERSION_LENS("Conversion Lens"),
    IMAGE_PROCESSING_VERSION("Image Processing Version"),
    DISTORTION_CORRECTION_2("Distortion Correction 2"),
    EXTENDER("Extender"),
    AF_SEARCH("AF Search"),
    PHOTO_STYLE("Photo Style"),
    RAW_DEV_CONTRAST_VALUE("Raw Dev Contrast Value"),
    MAKERNOTE_UNKNOWN_8("Makernote Unknown 8"),
    WHITE_BALANCE_BLUE("White Balance (Blue)"),
    PREVIEW_IMAGE_START("Preview Image Start"),
    COLOR_TEMP_KELVIN("Color Temp Kelvin"),
    RAW_DATA_BYTE_ORDER("Raw Data Byte Order"),
    MAX_FACES("Max Faces"),
    IS_COLOR_TABLE_SORTED("Is Color Table Sorted"),
    SCENE_AREA("Scene Area"),
    KEYSTONE_VALUE("Keystone Value"),
    LENS_FIRMWARE_VERSION("Lens Firmware Version"),
    CASIO_PREVIEW_THUMBNAIL("Casio Preview Thumbnail"),
    ONE_TOUCH_WB("One Touch WB"),
    PLANES("Planes"),
    MAX_APERTURE_AT_MIN_FOCAL("Max Aperture At Min Focal"),
    FACE_DETECT_FRAME_CROP("Face Detect Frame Crop"),
    EASY_MODE("Easy Mode"),
    WHITE_BOARD("White Board"),
    HAS_GLOBAL_COLOR_TABLE("Has Global Color Table"),
    INTERNAL_SERIAL_NUMBER("Internal Serial Number"),
    INTERNAL_FLASH("Internal Flash"),
    HEIGHT("Height"),
    FLASH_WARNING("Flash Warning"),
    MONTH_DAY_CREATED("Month/Day Created"),
    LENS_PROPERTIES("Lens Properties"),
    FLASH_EXPOSURE_COMP("Flash Exposure Comp"),
    AF_FINE_TUNE_ADJ("AF Fine Tune Adj"),
    WHITE_BALANCE_BRACKET("White Balance Bracket"),
    RECOGNIZED_FACE_FLAGS("Recognized Face Flags"),
    SCALE("Scale"),
    BITMAP_TYPE("Bitmap type"),
    FLASH_CURTAIN("Flash Curtain"),
    LENS_MOUNT("Lens Mount"),
    RAW_DEV_COLOR_SPACE("Raw Dev Color Space"),
    SHUTTER_COUNT("Shutter Count"),
    FLASH_STRENGTH("Flash Strength"),
    TEXT_STAMP_3("Text Stamp 3"),
    PICTURE_MODE_SATURATION("Picture Mode Saturation"),
    BURST_SPEED("Burst Speed"),
    BLUR_WARNING("Blur Warning"),
    RAW_DEV_SHARPNESS_VALUE("Raw Dev Sharpness Value"),
    MAKERNOTE_UNKNOWN_3("Makernote Unknown 3"),
    COLOUR_MODE("Colour Mode"),
    FOCUS_STEP_INFINITY("Focus Step Infinity"),
    COLOR_MATRIX("Color Matrix"),
    FLASH_DISTANCE("Flash Distance"),
    MANOMETER_READING("Manometer Reading"),
    THUMBNAIL_DIMENSIONS("Thumbnail Dimensions"),
    TONING_SATURATION("Toning Saturation"),
    CONTRAST_SETTING("Contrast Setting"),
    SHARPNESS_SETTING("Sharpness Setting"),
    AF_ASSIST_LAMP("AF Assist Lamp"),
    MIN_FOCAL_LENGTH("Min Focal Length"),
    SONY_EXPOSURE_TIME("Sony Exposure Time"),
    LIVE_PHOTO_ID("Live Photo ID"),
    TONE_LEVEL("Tone Level"),
    Y_PIXELS_PER_METER("Y Pixels per Meter"),
    RAW_DEV_ENGINE("Raw Dev Engine"),
    FACE_DETECTION_INFO("Face Detection Info"),
    ISO_SENSITIVITY("ISO Sensitivity"),
    STACKED_IMAGE("Stacked Image"),
    SERIAL_NUMBER("Serial Number"),
    INTELLIGENT_RESOLUTION("Intelligent Resolution"),
    LENS_DISTORTION_PARAMETERS("Lens Distortion Parameters"),
    ROLL_ANGLE("Roll Angle"),
    ACCELEROMETER_X("Accelerometer X"),
    SWEEP_PANORAMA_DIRECTION("Sweep Panorama Direction"),
    MAKERNOTE_VERSION("Makernote Version"),
    FOCUS_DISTANCE("Focus Distance"),
    HDR_IMAGE_TYPE("HDR Image Type"),
    PICTURE_CONTROL_NAME("Picture Control Name"),
    CITY("City"),
    CAMERA_ORIENTATION("Camera Orientation"),
    VALUE("Value"),
    FLASH_SERIAL_NUMBER("Flash Serial Number"),
    NOISE_REDUCTION_2("Noise Reduction 2"),
    MAKERNOTE_UNKNOWN_7("Makernote Unknown 7"),
    BITS_PER_PIXEL1("Bits per Pixel"),
    TEXT_STAMP("Text Stamp"),
    PREVIEW_IMAGE_LENGTH("Preview Image Length"),
    NOISE_FILTER("Noise Filter"),
    ENHANCEMENT("Enhancement"),
    CROP_LEFT("Crop Left"),
    ART_FILTER_EFFECT("Art Filter Effect"),
    SCENE_DETECT("Scene Detect"),
    INTERNAL_ND_FILTER("Internal ND Filter"),
    MAGIC_FILTER("Magic Filter"),
    SONY_F_NUMBER("Sony F Number"),
    THUMBNAIL_SIZE("Thumbnail Size"),
    PICTURE_CONTROL_ADJUST("Picture Control Adjust"),
    TOTAL_ZOOM("Total Zoom"),
    MANOMETER_PRESSURE("Manometer Pressure"),
    FACE_DETECT("Face Detect"),
    TRAVEL_DAY("Travel Day"),
    CROP_TOP("Crop Top"),
    EXTERNAL_FLASH_BOUNCE("External Flash Bounce"),
    AF_POINT("AF Point"),
    LEFT("Left"),
    PICTURE_CONTROL_VERSION("Picture Control Version"),
    COLOR_TABLE_SIZE("Color Table Size"),
    HUE("Hue"),
    FOCAL_PLANE_DIAGONAL("Focal Plane Diagonal"),
    TONING_EFFECT("Toning Effect"),
    CAMERA_ID("Camera Id"),
    PRE_CAPTURE_FRAMES("Pre Capture Frames"),
    RAW_DEV_EXPOSURE_BIAS_VALUE("Raw Dev Exposure Bias Value"),
    BABY_NAME("Baby Name"),
    FACE_DETECT_FRAME_SIZE("Face Detect Frame Size"),
    AF_FINE_TUNE("AF Fine Tune"),
    BABY_AGE("Baby Age"),
    SHUTTER("Shutter"),
    MAKERNOTE_UNKNOWN_2("Makernote Unknown 2"),
    COLOR_CREATOR_EFFECT("Color Creator Effect"),
    RAW_DEV_EDIT_STATUS("Raw Dev Edit Status"),
    WHITE_BALANCE_GREEN("White Balance (Green)"),
    BESTSHOT_MODE("BestShot Mode"),
    INTELLIGENT_EXPOSURE("Intelligent Exposure"),
    CAMERA_SETTINGS_VERSION("Camera Settings Version"),
    EXPOSURE_SHIFT("Exposure Shift"),
    SHUTTER_SPEED("Shutter Speed"),
    IMPORTANT_COLOUR_COUNT("Important Colour Count"),
    BITS_PER_PIXEL2("Bits Per Pixel"),
    COMPRESSION_FACTOR("Compression Factor"),
    RAW_DEV_WB_FINE_ADJUSTMENT("Raw Dev WB Fine Adjustment"),
    LENS_FORMAT("Lens Format"),
    DISTORTION_CORR_PARAMS_PRESENT("Distortion Corr Params Present"),
    WHITE_BALANCE_ADJUST_AB("White Balance Adjust (AB)"),
    PICTURE_MODE_TONE("Picture Mode Tone"),
    RAW_DEV_VERSION("Raw Dev Version"),
    TEXT_STAMP_2("Text Stamp 2"),
    WHITE_BALANCE_BIAS("White Balance Bias"),
    RAW_DEV_WHITE_BALANCE_VALUE("Raw Dev White Balance Value"),
    TOP("Top"),
    KODAK_MODEL("Kodak Model"),
    ROTATION("Rotation"),
    AUTO_FOCUS("Auto Focus"),
    PICTURE_MODE_HUE("Picture Mode Hue"),
    AE_LOCK("AE Lock"),
    FLASH_REMOTE_CONTROL("Flash Remote Control"),
    GRADATION("Gradation"),
    FLASH_BIAS("Flash Bias"),
    RAW_DATA_CFA_PATTERN("Raw Data CFA Pattern"),
    FLAGS("Flags"),
    HUE_ADJUSTMENT("Hue Adjustment"),
    CROP_HEIGHT("Crop Height"),
    EQUIPMENT_VERSION("Equipment Version"),
    MANUAL_FLASH("Manual Flash"),
    BABY_AGE_1("Baby Age 1"),
    LENS_TYPE_2("Lens Type 2"),
    ACCELERATION_VECTOR("Acceleration Vector"),
    SHADING_COMPENSATION_2("Shading Compensation 2"),
    CLEAR_RETOUCH_VALUE("Clear Retouch Value"),
    AF_INFO("AF Info"),
    FACES_DETECTED("Faces Detected"),
    EXTERNAL_FLASH_ZOOM("External Flash Zoom"),
    PICTURE_MODE("Picture Mode"),
    DELAY("Delay"),
    CROP_WIDTH("Crop Width"),
    DISPOSAL_METHOD("Disposal Method"),
    CLARITY("Clarity"),
    EXTERNAL_FLASH_GUIDE_NUMBER("External Flash Guide Number"),
    SLOW_SYNC("Slow Sync"),
    STATE("State"),
    RAW_DEV_SATURATION_EMPHASIS("Raw Dev Saturation Emphasis"),
    MAX_APERTURE_AT_MAX_FOCAL("Max Aperture At Max Focal"),
    YEAR_CREATED("Year Created"),
    WHITE_BALANCE_RED("White Balance (Red)"),
    IMAGE_STABILIZATION("Image Stabilization"),
    FILTER_EFFECT("Filter Effect"),
    OPTICAL_ZOOM_MODE("Optical Zoom Mode"),
    CCD_SENSITIVITY("CCD Sensitivity"),
    MAKERNOTE_UNKNOWN_5("Makernote Unknown 5"),
    CCD_ISO_SENSITIVITY("CCD ISO Sensitivity"),
    AE_WARNING("AE Warning"),
    CAMERA_TYPE_2("Camera Type 2"),
    BLACK_LEVEL_2("Black Level 2"),
    PICTURE_CONTROL_QUICK_ADJUST("Picture Control Quick Adjust"),
    OBJECT_DISTANCE("Object Distance"),
    AUTO_BRACKETING("Auto Bracketing"),
    FLASH_FIRMWARE_VERSION("Flash Firmware Version"),
    FLASH_CONTROL_MODE("Flash Control Mode"),
    BODY_FIRMWARE_VERSION("Body Firmware Version"),
    FOCUS_INFO_VERSION("Focus Info Version"),
    IS_INTERLACED("Is Interlaced"),
    CUSTOM_SATURATION("Custom Saturation"),
    SHADING_COMPENSATION("Shading Compensation"),
    EXTENDER_MODEL("Extender Model"),
    FLASH_MODEL("Flash Model"),
    LOCATION("Location"),
    SENSOR_CALIBRATION("Sensor Calibration"),
    ND_FILTER("ND Filter"),
    NUMBER_OF_COMPONENTS("Number of Components"), // Number of image color components/channels.
    NUMBER_OF_TABLES("Number of Tables"), // Number of Huffman tables present.
    OBJECT_NAME("Object Name"), // IPTC object name/slug.
    OPTICAL_ZOOM_CODE("Optical Zoom Code"),
    PADDING("Padding"), // Padding bytes/data block.
    PHOTOMETRIC_INTERPRETATION("Photometric Interpretation"),
    PHOTO_EFFECT("Photo Effect"),
    PIXEL_ASPECT_RATIO("Pixel Aspect Ratio"),
    PRIMARY_PLATFORM("Primary Platform"), // Platform target recorded in ICC profile.
    PRINTIM_VERSION("PrintIM Version"),
    PRINT_FLAGS("Print Flags"),
    PRINT_FLAGS_INFORMATION("Print Flags Information"),
    PRINT_INFO_2("Print Info 2"),
    PRINT_SCALE("Print Scale"),
    PRINT_STYLE("Print Style"),
    PROFILE_CONNECTION_SPACE("Profile Connection Space"), // PCS used by ICC profile (e.g., XYZ/Lab).
    PROFILE_COPYRIGHT("Profile Copyright"), // Copyright notice for profile.
    PROFILE_DESCRIPTION("Profile Description"), // Human-readable profile description.
    PROFILE_SIZE("Profile Size"), // ICC profile size in bytes.
    QUALITY("Quality"),
    RATING("Rating"),
    RECORD_MODE("Record Mode"),
    RED_COLORANT("Red Colorant"), // Red primary colorant coordinates.
    RED_TRC("Red TRC"), // Red tone response curve definition.
    RELATED_IMAGE_HEIGHT("Related Image Height"),
    RELATED_IMAGE_WIDTH("Related Image Width"),
    RENDERING_INTENT("Rendering Intent"),
    RESOLUTION_INFO("Resolution Info"),
    SAMPLES_PER_PIXEL("Samples Per Pixel"),
    SATURATION("Saturation"),
    SCENE_CAPTURE_TYPE("Scene Capture Type"),
    SCENE_MODE("Scene Mode"),
    SCENE_TYPE("Scene Type"),
    SEED_NUMBER("Seed Number"),
    SELF_TIMER_2("Self Timer 2"),
    SELF_TIMER_DELAY("Self Timer Delay"),
    SENSING_METHOD("Sensing Method"),
    SENSITIVITY_TYPE("Sensitivity Type"),
    SEQUENCE_NUMBER("Sequence Number"),
    SHARPNESS("Sharpness"),
    SHORT_FOCAL_LENGTH("Short Focal Length"),
    SHUTTER_SPEED_VALUE("Shutter Speed Value"),
    SIGNATURE("Signature"), // ICC profile signature (e.g., acsp).
    SLICES("Slices"),
    SLOW_SHUTTER("Slow Shutter"),
    SOFTWARE("Software"), // Software used to create/edit image.
    SOURCE("Source"), // Source/origin information.
    SPECIAL_INSTRUCTIONS("Special Instructions"), // Rights/use instructions.
    SPOT_METERING_MODE("Spot Metering Mode"),
    SRAW_QUALITY("SRAW Quality"),
    SUB_SEC_TIME_ORIGINAL("Sub-Sec Time Original"), // Sub-second precision for original timestamp.
    SUPPLEMENTAL_CATEGORY_S("Supplemental Category(s)"), // Additional IPTC categories.
    TAG_COUNT("Tag Count"), // Number of ICC tags in profile.
    TARGET_APERTURE("Target Aperture"),
    TARGET_EXPOSURE_TIME("Target Exposure Time"),
    TELECONVERTER_MODEL("Teleconverter Model"),
    TEXTUAL_DATA("Textual Data"), // Embedded textual payload/comments/raw text blocks.
    THUMBNAIL_DATA("Thumbnail Data"),
    THUMBNAIL_HEIGHT_PIXELS("Thumbnail Height Pixels"), // Embedded thumbnail height.
    THUMBNAIL_IMAGE_VALID_AREA("Thumbnail Image Valid Area"),
    THUMBNAIL_LENGTH("Thumbnail Length"),
    THUMBNAIL_OFFSET("Thumbnail Offset"),
    THUMBNAIL_WIDTH_PIXELS("Thumbnail Width Pixels"), // Embedded thumbnail width.
    UNKNOWN_CAMERA_SETTING_2("Unknown Camera Setting 2"),
    UNKNOWN_CAMERA_SETTING_3("Unknown Camera Setting 3"),
    UNKNOWN_CAMERA_SETTING_7("Unknown Camera Setting 7"),
    USER_COMMENT("User Comment"),
    VERSION("Version"), // Metadata schema/profile version.
    VERSION_INFO("Version Info"),
    VRD_OFFSET("VRD Offset"),
    WHITE_BALANCE("White Balance"),
    WHITE_BALANCE_FINE_TUNE_VALUE("White Balance Fine Tune Value"),
    WHITE_BALANCE_MODE("White Balance Mode"),
    XMP_VALUE_COUNT("XMP Value Count"), // Number of extracted XMP values.
    XYZ_VALUES("XYZ values"), // Profile XYZ tristimulus reference values.
    YCBCR_POSITIONING("YCbCr Positioning"), // YCbCr sampling positioning.
    ZONE_MATCHING("Zone Matching"),
    ZOOM_SOURCE_WIDTH("Zoom Source Width"),
    ZOOM_TARGET_WIDTH("Zoom Target Width")
    ;

    private final String name;
    private final boolean includeInSummary;
    private static final Map<String, MetadataTagEnum> byName = new HashMap<>();

    MetadataTagEnum(String name) {
        this(name, false);
    }

    MetadataTagEnum(String name, boolean includeInSummary) {
        this.name = name;
        this.includeInSummary = includeInSummary;
    }

    public String getName() {
        return name;
    }

    public boolean isIncludeInSummary() {
        return includeInSummary;
    }

    public static MetadataTagEnum getByName(String name) {
        if (byName.isEmpty()) {
            for (MetadataTagEnum tag : values()) {
                byName.put(tag.name, tag);
            }
        }
        return byName.get(name);
    }
}
